project:
  type: website
  output-dir: docs

website:
  title: "Thomas Hudson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - project.qmd
    
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/thomas-m-hudson/
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/hudsontm/hudsontm.quartowebdemo

format:
  html:
    theme: zephyr #flatly, litera, lumen, lux, minty, pulse, sandstone, zephyr, quartz, yeti, cosmo, sketchy
    css: styles.css
    toc: true

execute: 
  freeze: auto

