{
  "hash": "c34d6adcb96aaa0b369673fcf44c7668",
  "result": {
    "markdown": "---\ntitle: \"Partial Replication of [Bicycle Sharing in Seattle](https://amber.rbind.io/2016/11/10/bicyclesseattle/)\"\ndate: last-modified\ndate-format: \"[Last modified on] MMMM DD, YYYY HH:mm:ss zzz\"\nformat: \n  html:\n    theme: cosmo  # zephyr pulse, sketchy, default, cosmo, vapor etc\nauthor:\n  - name: Thomas Hudson\n    email: hudsontm@appstate.edu\n    affiliation:\n      - name: Appalachian State University\n        city: Boone\n        state: NC  \n        url: https://www.appstate.edu/\nabstract: >\n  This is a replication of select portions of Amber Thomas's original post [Bicycle Sharing in Seattle](https://amber.rbind.io/2016/11/10/bicyclesseattle/) from November 10, 2016.\nkeywords:\n  - R\n  - data viz\nlicense: \"CC BY\"  \ncode-fold: false\n---\n\n\n![Someone is bikepacking!](./pics/bikePacking.jpg)\n\n\n# Introduction\n\nThis is an exploration of bicycle-sharing data in the city of Seattle, WA (USA) from **October 2014 - April 2015** not the data Amber used that was **October 2014 - August 2016**. I hope to eventually combine this data with other forms of ride-sharing and transportation in the city, but this will be the first step.\n\nTime to get started!\n\n\n\n\n\n## Loading Necessary Packages\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# For data manipulation and tidying\nlibrary(dplyr)\nlibrary(lubridate)\nlibrary(tidyr)\n\n# For mapping\nlibrary(ggmap)\nlibrary(mapproj)\n\n# For data visualizations\nlibrary(ggplot2)\n\n# For modeling and machine learning\nlibrary(caret)\n```\n:::\n\n\n## Importing Data\n\nAll of the data can be downloaded from [Kaggle](https://www.kaggle.com/pronto/cycle-share-dataset). This project contains 3 data sets and each file is imported and inspected independently using the `read.csv()` function.\n\n:::{.callout-warning}\nThe data from [Kaggle](https://www.kaggle.com/pronto/cycle-share-dataset) is not the same data that was originally analyzed by Amber.  Specifically, the number of rows in the `trip` dataset downloaded from Kaggle is 50,793 compared to the 236,065 rows Amber analyzes.  The Pronto web site for Seattle is no longer available. \n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nstation <- read.csv(file = \"./data/station.csv\",\n                    header = TRUE,\n                    stringsAsFactors = FALSE)\n\ntrip <- read.csv(file = \"./data/trip.csv\",\n                 header = TRUE,\n                 stringsAsFactors = FALSE)\n\nweather <- read.csv(file = \"./data/weather.csv\",\n                    header = TRUE,\n                    stringsAsFactors = FALSE)\n```\n:::\n\n\nOk, let's take a look at each of these data files.\n\n### Data Structures and Variables\n\n#### `station`\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n```\nRows: 58\nColumns: 9\n$ station_id        <chr> \"BT-01\", \"BT-03\", \"BT-04\", \"BT-05\", \"CBD-03\", \"CBD-0…\n$ name              <chr> \"3rd Ave & Broad St\", \"2nd Ave & Vine St\", \"6th Ave …\n$ lat               <dbl> 47.61842, 47.61583, 47.61609, 47.61311, 47.61073, 47…\n$ long              <dbl> -122.3510, -122.3486, -122.3411, -122.3442, -122.332…\n$ install_date      <chr> \"10/13/2014\", \"10/13/2014\", \"10/13/2014\", \"10/13/201…\n$ install_dockcount <int> 18, 16, 16, 14, 20, 18, 20, 20, 20, 18, 16, 16, 18, …\n$ modification_date <chr> \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"11/9/2015\", \"\", \"\", \"8/…\n$ current_dockcount <int> 18, 16, 16, 14, 20, 18, 20, 18, 20, 18, 0, 16, 20, 1…\n$ decommission_date <chr> \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"8/9/2016\", …\n```\n:::\n:::\n\n\nThere are 9 variables in the data `station` data frame:\n\n1. `station_id`: The individual ID number for a bike station\n\n2. `name`: The name of that station ID, also appears to be the rough location of the station\n\n3. `lat`: The latitude of the station\n\n4. `long`: The longitude of the station\n\n5. `install_date`: Date that station was placed in service (MM/DD/YYYY format)\n\n6. `install_dockcount`: Number of docks (bike positions) at each station on the installation date\n\n7. `modification_date`: Date that station was modified, resulting in a change in location or dock count (MM/DD/YYYY format)\n\n8. `current_dockcount`: Number of docks at each station on 8/31/2016\n\n9. `decommission_date`: Date that station was placed out of service (MM/DD/YYYY format)\n\n#### `trip`\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n```\nRows: 50,793\nColumns: 12\n$ trip_id           <int> 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 44…\n$ starttime         <chr> \"10/13/2014 10:31\", \"10/13/2014 10:32\", \"10/13/2014 …\n$ stoptime          <chr> \"10/13/2014 10:48\", \"10/13/2014 10:48\", \"10/13/2014 …\n$ bikeid            <chr> \"SEA00298\", \"SEA00195\", \"SEA00486\", \"SEA00333\", \"SEA…\n$ tripduration      <dbl> 985.935, 926.375, 883.831, 865.937, 923.923, 808.805…\n$ from_station_name <chr> \"2nd Ave & Spring St\", \"2nd Ave & Spring St\", \"2nd A…\n$ to_station_name   <chr> \"Occidental Park / Occidental Ave S & S Washington S…\n$ from_station_id   <chr> \"CBD-06\", \"CBD-06\", \"CBD-06\", \"CBD-06\", \"CBD-06\", \"C…\n$ to_station_id     <chr> \"PS-04\", \"PS-04\", \"PS-04\", \"PS-04\", \"PS-04\", \"PS-04\"…\n$ usertype          <chr> \"Member\", \"Member\", \"Member\", \"Member\", \"Member\", \"M…\n$ gender            <chr> \"Male\", \"Male\", \"Female\", \"Female\", \"Male\", \"Male\", …\n$ birthyear         <int> 1960, 1970, 1988, 1977, 1971, 1974, 1978, 1983, 1974…\n```\n:::\n:::\n\nThere are 12 variables in the `trip` data frame.\n\n  1. `trip_id`: An identification number assigned to each trip (from one bike station to another)\n\n  2. `starttime`: The time and date that a bike was borrowed from a station (in MM/DD/YYYY HH:MM format)\n\n  3. `stoptime`: The time and date that a bike was returned to a station (in MM/DD/YYYY HH:MM format)\n\n  4. `bikeid`: The identification number for a specific bike\n\n  5. `tripduration`: Time of trip (measured in seconds)\n\n  6. `from_station_name`: The name of the station where the bike was borrowed from\n\n  7. `to_station_name`: The name of the station where the bike was returned to\n\n  8. `from_station_id`: The ID number of the station where the bike was borrowed from\n\n  9. `to_station_id`: The ID number of the station where the bike was returned to\n\n  10. `usertype`: Indicates whether the user was a Member'' (i.e., someone with a monthly or annual membership to Pronto!) or aShort-Term Pass Holder’’ (i.e., someone who purchased a 24 hour or 3 day pass)\n\n  11. `gender`: The gender of the rider (if known)\n\n  12. `birthyear`: The year that the rider was born\n  \n#### `weather`\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n```\nRows: 689\nColumns: 21\n$ Date                       <chr> \"10/13/2014\", \"10/14/2014\", \"10/15/2014\", \"…\n$ Max_Temperature_F          <int> 71, 63, 62, 71, 64, 68, 73, 66, 64, 60, 62,…\n$ Mean_Temperature_F         <int> 62, 59, 58, 61, 60, 64, 64, 60, 58, 58, 55,…\n$ Min_TemperatureF           <int> 54, 55, 54, 52, 57, 59, 55, 55, 55, 57, 50,…\n$ Max_Dew_Point_F            <int> 55, 52, 53, 49, 55, 59, 57, 57, 52, 55, 49,…\n$ MeanDew_Point_F            <int> 51, 51, 50, 46, 51, 57, 55, 54, 49, 53, 47,…\n$ Min_Dewpoint_F             <int> 46, 50, 46, 42, 41, 55, 53, 50, 46, 48, 44,…\n$ Max_Humidity               <int> 87, 88, 87, 83, 87, 90, 94, 90, 87, 88, 86,…\n$ Mean_Humidity              <int> 68, 78, 77, 61, 72, 83, 74, 78, 70, 81, 76,…\n$ Min_Humidity               <int> 46, 63, 67, 36, 46, 68, 52, 67, 58, 67, 62,…\n$ Max_Sea_Level_Pressure_In  <dbl> 30.03, 29.84, 29.98, 30.03, 29.83, 29.96, 2…\n$ Mean_Sea_Level_Pressure_In <dbl> 29.79, 29.75, 29.71, 29.95, 29.78, 29.90, 2…\n$ Min_Sea_Level_Pressure_In  <dbl> 29.65, 29.54, 29.51, 29.81, 29.73, 29.80, 2…\n$ Max_Visibility_Miles       <int> 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,…\n$ Mean_Visibility_Miles      <int> 10, 9, 9, 10, 10, 8, 10, 10, 10, 6, 10, 10,…\n$ Min_Visibility_Miles       <int> 4, 3, 3, 10, 6, 2, 6, 5, 6, 2, 10, 8, 6, 10…\n$ Max_Wind_Speed_MPH         <int> 13, 10, 18, 9, 8, 10, 10, 12, 15, 14, 15, 8…\n$ Mean_Wind_Speed_MPH        <int> 4, 5, 7, 4, 3, 4, 3, 5, 8, 8, 9, 4, 6, 12, …\n$ Max_Gust_Speed_MPH         <chr> \"21\", \"17\", \"25\", \"-\", \"-\", \"-\", \"18\", \"-\",…\n$ Precipitation_In           <dbl> 0.00, 0.11, 0.45, 0.00, 0.14, 0.31, 0.00, 0…\n$ Events                     <chr> \"Rain\", \"Rain\", \"Rain\", \"Rain\", \"Rain\", \"Ra…\n```\n:::\n:::\n\n\nThere are 21 variables in the `weather` data frame:\n\n  1. `Date`: The date in MM/DD/YYYY format\n  \n  2. `Max_Temperature_F`: The maximum temperature that day (in degrees F)\n\n  3. `Mean_Temperature_F`: The average temperature that day (in degrees F)\n\n  4. `Min_TemperatureF` : The minimum temperature that day (in degrees F)\n\n  5. `Max_Dew_Point_F`: The maximum dew point (in degrees F)\n\n  6. `MeanDew_Point_F`: The average dew point (in degrees F)\n\n  7. `Min_Dewpoint_F` : The minimum dew point (in degrees F)\n\n  8. `Max_Humidity`: The maximum humidity (in %)\n\n  9. `Mean_Humidity`: The average humidity (in %)\n\n  10. `Min_Humidity`: The minimum humidity (in %)\n  \n  11. `Maximum_Sea_Level_Pressure_In` : The maximum atmospheric pressure at sea level (in inches of mercury)\n\n  12. `Mean_Sea_Level_Pressure_In`: The average atmospheric pressure at sea level (in inches of mercury)\n\n  13. `Min_Sea_Level_Pressure_In`: The minimum atmospheric pressure at sea level (in inches of mercury)\n\n  14. `Max_Visibility_Miles`: The maximum visibility (in miles)\n\n  15. `Mean_Visibility_Miles`: The average visibility (in miles)\n\n  16. `Min_Visibility_Miles`: The minimum visibility (in miles)\n\n  17. `Max_Wind_Speed_MPH`: The maximum sustained wind speed (in miles per hour)\n\n  18. `Mean_Wind_Speed_MPH`: The average sustained wind speed (in miles per hour)\n\n  19. `Max_Gust_Speed_MPH`: The maximum gust wind speed (in miles per hour)\n\n  20. `Precipitation_In`: The amount of precipitation (measured in inches)\n\n  21. `Events`: Weather events that occurred that day (e.g., rain, fog, snow, thunderstorm etc.)\n  \n# Data Visualization\n\n## Exploring the `station` Dataset\n\nSince the `station` dataset was the first one imported, let’s start with a little exploration there. First of all, how many unique stations are we dealing with?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nS1 <- station |>\n  summarize(nds = n_distinct(station_id))\nS1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  nds\n1  58\n```\n:::\n:::\n\nThere are 58 different stations. @fig-map1 shows where the stations are located.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nstation |>\n  group_by(station_id) |> \n  head()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 9\n# Groups:   station_id [6]\n  station_id name     lat  long install_date install_dockcount modification_date\n  <chr>      <chr>  <dbl> <dbl> <chr>                    <int> <chr>            \n1 BT-01      3rd A…  47.6 -122. 10/13/2014                  18 \"\"               \n2 BT-03      2nd A…  47.6 -122. 10/13/2014                  16 \"\"               \n3 BT-04      6th A…  47.6 -122. 10/13/2014                  16 \"\"               \n4 BT-05      2nd A…  47.6 -122. 10/13/2014                  14 \"\"               \n5 CBD-03     7th A…  47.6 -122. 10/13/2014                  20 \"\"               \n6 CBD-04     Union…  47.6 -122. 7/27/2015                   18 \"\"               \n# ℹ 2 more variables: current_dockcount <int>, decommission_date <chr>\n```\n:::\n\n```{.r .cell-code}\nstation_locs <- station |>\n  group_by(station_id) |> \n  select(station_id, lat, long)\nstation_locs\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 58 × 3\n# Groups:   station_id [58]\n   station_id   lat  long\n   <chr>      <dbl> <dbl>\n 1 BT-01       47.6 -122.\n 2 BT-03       47.6 -122.\n 3 BT-04       47.6 -122.\n 4 BT-05       47.6 -122.\n 5 CBD-03      47.6 -122.\n 6 CBD-04      47.6 -122.\n 7 CBD-05      47.6 -122.\n 8 CBD-06      47.6 -122.\n 9 CBD-07      47.6 -122.\n10 CBD-13      47.6 -122.\n# ℹ 48 more rows\n```\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n\n````{.cell-code}\n```{{r}}\n#| label: fig-map1\n#| fig-cap: \"Seattle bike station locations\"\n# Load the correct map\n# mymap <- get_map(location = \"Seattle\", maptype = \"roadmap\", zoom = 12)\n\n# Plot a single point for each Station ID\n# ggmap(mymap) + geom_point(aes(x = long, y = lat), data = station_locs, \n#    alpha = 0.7, color = \"darkred\", size = 2)\n```\n````\n:::\n\n\nSo it looks like all of the stations are located near the Lower Queen Anne, Belltown, International District, Capitol Hill and University of Washington areas. @fig-mymap2 provides a more zoomed-in view of the bike station locations.\n\n\n::: {.cell layout-align=\"center\"}\n\n````{.cell-code}\n```{{r}}\n#| label: fig-mymap2\n#| fig-cap: \"Zoomed in view of Seattle bike station locations\"\n# mymap2 <- get_map(location = c(lon = -122.32, lat = 47.63),\n                    # maptype = \"roadmap\", zoom = 13)\n# Plot a single point for each Station ID\n# ggmap(mymap2) + geom_point(\n#   aes(x = long, y = lat),\n#   data = station_locs,\n#   alpha = 0.5,\n#   color = \"red\",\n#   size = 2\n# )\n```\n````\n:::\n\n\nThe bike locations appear clustered in @fig-mymap2. It would be interesting to know the order the stations were added.\n\n\n### Station Installations\n\nFirst, let’s convert those character-string date objects to actual dates using the `lubridate` package.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nstation$install_date <- mdy(station$install_date)\n# How many times were new stations installed?\nstation |>  \n  summarise(n_distinct(install_date))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  n_distinct(install_date)\n1                        9\n```\n:::\n\n```{.r .cell-code}\n# How many stations were installed on each date?\nstation |>  \n  group_by(install_date) |>  \n  summarise(count = n()) |>  \n  arrange(install_date)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 9 × 2\n  install_date count\n  <date>       <int>\n1 2014-10-13      50\n2 2015-05-22       1\n3 2015-06-12       1\n4 2015-07-27       1\n5 2015-09-15       1\n6 2015-10-29       1\n7 2016-03-18       1\n8 2016-07-03       1\n9 2016-08-09       1\n```\n:::\n:::\n\n\nThe majority (86.21%) of the stations were added on opening day. @fig-mymap3 shows the location of the original bike stations and @fig-mymap4 shows the location and date additional bike stations were added.\n\n\n::: {.cell layout-align=\"center\"}\n\n````{.cell-code}\n```{{r}}\n#| label: fig-mymap3\n#| fig-cap: \"Original bike stations\"\n# Plot a single point for each Station ID originally installed 2014-10-13\n# ggmap(mymap2) +\n#   geom_point(\n#     aes(x = long, y = lat),\n#     data = subset(station, install_date == \"2014-10-13\"),\n#     alpha = 0.5,\n#     color = \"red\",\n#     size = 2\n#   )\n```\n````\n:::\n\n::: {.cell layout-align=\"center\"}\n\n````{.cell-code}\n```{{r}}\n#| label: fig-mymap4\n#| fig-cap: \"Subsequently added bike stations\"\n# ggmap(mymap2) +\n#   geom_point(\n#     aes(\n#       x = long,\n#       y = lat,\n#       color = factor(install_date)\n#     ),\n#     data = subset(station, install_date != \"2014-10-13\"),\n#     size = 3\n#   ) +\n#   theme(\n#     legend.position = c(0.95, 0.05),\n#     legend.justification = c(0.95, 0.05)\n#   ) +\n#   labs(color = \"Install Date\")\n```\n````\n:::\n\n\nSo they added more stations throughout the district that they serve, instead of adding several new stations to a single neighborhood all at once. Good to know.\n\nThe number of bikes parked at each station (as of August 31, 2016) is shown in @fig-graph1.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Bar graph showing that most bike stations currently house between 14 and 20 bikes.](BikeSharing_files/figure-html/fig-graph1-1.png){#fig-graph1 fig-align='center' width=672}\n:::\n:::\n\n\nWell that’s weird, some of the stations have a dock count of 0. I’m assuming they didn’t start that way. Let’s calculate the change in dock count from station installation to August 31, 2016 and plot it in @fig-change.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndock_change <- station  |>\n  group_by(station_id)  |>\n  select(station_id, long, lat, ends_with(\"dockcount\")) |>\n  mutate(dock_change = current_dockcount - install_dockcount)\n```\n:::\n\n\n11 stations lost bike docks, 39 stayed the same, and 8 stations gained docks.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nxtabs(~ dock_change, data = dock_change)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ndock_change\n-20 -16  -6  -4  -2   0   2   4   6   8 \n  1   3   2   1   4  39   4   2   1   1 \n```\n:::\n:::\n\n\n### Current Station Size\n\n@fig-size examines the current size of each station.\n\nSo it looks like the biggest stations tend to be on the outskirts of the rest. Where there are several stations in close proximity, there tend to be fewer bike docks at each station. That makes sense, logically speaking. If you go to a station and there is no bike to rent, you can easily go to another nearby, assuming there is another nearby. In areas where the stations are more secluded, it’s more important that there be bikes and open spaces readily available for users.\n\nAlright, I’m feeling good about exploring this dataset. Time to check out the trip dataset!\n\n## Exploring the `trip` dataframe\n\nA `glimpse` of the `trip` data frame is provided below.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n```\nRows: 50,793\nColumns: 12\n$ trip_id           <int> 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 44…\n$ starttime         <chr> \"10/13/2014 10:31\", \"10/13/2014 10:32\", \"10/13/2014 …\n$ stoptime          <chr> \"10/13/2014 10:48\", \"10/13/2014 10:48\", \"10/13/2014 …\n$ bikeid            <chr> \"SEA00298\", \"SEA00195\", \"SEA00486\", \"SEA00333\", \"SEA…\n$ tripduration      <dbl> 985.935, 926.375, 883.831, 865.937, 923.923, 808.805…\n$ from_station_name <chr> \"2nd Ave & Spring St\", \"2nd Ave & Spring St\", \"2nd A…\n$ to_station_name   <chr> \"Occidental Park / Occidental Ave S & S Washington S…\n$ from_station_id   <chr> \"CBD-06\", \"CBD-06\", \"CBD-06\", \"CBD-06\", \"CBD-06\", \"C…\n$ to_station_id     <chr> \"PS-04\", \"PS-04\", \"PS-04\", \"PS-04\", \"PS-04\", \"PS-04\"…\n$ usertype          <chr> \"Member\", \"Member\", \"Member\", \"Member\", \"Member\", \"M…\n$ gender            <chr> \"Male\", \"Male\", \"Female\", \"Female\", \"Male\", \"Male\", …\n$ birthyear         <int> 1960, 1970, 1988, 1977, 1971, 1974, 1978, 1983, 1974…\n```\n:::\n:::\n\n\nGreat, so there are quite a few things that we can potentially look at using this dataset by itself. Let’s start with the number of trips per day since Pronto! began opening bike stations. To do that, we need to recode our start date/times as `POSIXct` objects. We’ll use the `lubridate` package for this.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Make the start and stop dates into POSIXct objects\ntrip_2 <- trip |>\n  mutate(start_dt = mdy_hm(starttime),\n         stop_dt = mdy_hm(stoptime))\n\n# Recode the dates\ntrip_2 <- trip_2 |>\n  mutate(start_date = paste(month(start_dt),\n         day(start_dt), year(start_dt), sep = \"/\"))\ntrip_2$start_date <- mdy(trip_2$start_date)\n\ntrip_2 <- trip_2 |>\n  mutate(stop_date = paste(month(stop_dt),\n         day(stop_dt), year(stop_dt), sep = \"/\"))\ntrip_2$stop_date <- mdy(trip_2$stop_date)\n```\n:::\n\n\nGreat! The number of rides per day is shown in @fig-graph2.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Line graph with LOESS smoother showing daily fluctuations in the number of trips made per day.](BikeSharing_files/figure-html/fig-graph2-1.png){#fig-graph2 fig-align='center' width=672}\n:::\n:::\n\n\n### Plotting Trips Per Month (By Season)\nFirst, we create a “Year-Month” variable as well as a “Season” variable.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nstart_date_ym <- trip_2  |>\n  mutate(\n    ym = paste(year(start_date),\n               month(start_date),\n               sep = \"/\"),\n    Season = case_when(\n      ym %in% c(\"2014/10\", \"2014/11\") ~ \"Fall\",\n      ym %in% c(\"2014/12\", \"2015/1\", \"2015/2\") ~ \"Winter\",\n      ym %in% c(\"2015/3\", \"2015/4\", \"2015/5\") ~ \"Spring\"\n    )\n  )\n```\n:::\n\n\nNow plot. I think I’ll plot this by month but color it by season (where December, January, and February are “Winter”, March, April, and May are “Spring”, and October, and November are “Fall”).\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Line graph showing the number of trips taken per month over the course of the year and colored by season.](BikeSharing_files/figure-html/fig-graph3-1.png){#fig-graph3 fig-align='center' width=672}\n:::\n:::\n\n\nWell the kaggle data is quite different from the data used by Amber!\n\n### Average Trip Duration\nGreat! I wonder how the average trip duration fluctuates over this time period.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Convert Trip Duration from Seconds to Minutes\nTrip_Duration_Month <- start_date_ym |>\n  mutate(trip_duration_min = tripduration / 60) |>\n  group_by(ym) |>\n  select(ym, trip_duration_min, Season) |>\n  summarize(Avg = mean(trip_duration_min),\n            sd = sd(trip_duration_min)) |>\n  mutate(\n    se = sd / sqrt(n()),\n    Season = case_when(\n      ym %in% c(\"2014/10\", \"2014/11\") ~ \"Fall\",\n      ym %in% c(\"2014/12\", \"2015/1\", \"2015/2\") ~ \"Winter\",\n      ym %in% c(\"2015/3\", \"2015/4\", \"2015/5\") ~ \"Spring\"\n    )\n  )\n```\n:::\n\n\nNow to plot the average trip duration (in minutes) ($\\pm SE$)), with colors indicating seasons.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![A line graph showing the duration (with standard error bars) of the average trip per month, colored for each season.](BikeSharing_files/figure-html/fig-graph4-1.png){#fig-graph4 fig-align='center' width=672}\n:::\n:::\n\n\n### Number of Trips by Day of Week\nI wonder if people are using this service to commute to/from work. Let’s look at the number of trips by day of the week.\n\nFirst, let’s create a Day of the Week variable.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nstart_date_ym$wd <- wday(start_date_ym$start_date, label = TRUE)\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![A line graph showing number of trips taken by day of the week. There are more trips taken Monday - Friday.](BikeSharing_files/figure-html/fig-graph5-1.png){#fig-graph5 fig-align='center' width=672}\n:::\n:::\n\n\nOk, so there are definitely more trips during the week than on the weekends. I wonder if this varies by season too.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Line graph with a line for each season showing the number of trips taken by day of the week.](BikeSharing_files/figure-html/fig-graph6-1.png){#fig-graph6 fig-align='center' width=672}\n:::\n:::\n\n\n\nSo it looks like usage is some what consistent across Winter and Spring, at least as far as the number of trips are concerned.\n\n### Number of Trips by Time of Day\nHow about time of day? Are people using the bikes around commuting times during the week and later in the day on weekends?\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Seven, side-by-side graphs one for each day of the week. Each has a separate line for each of the three seasons, showing activity by hour of the day. Weekdays have spikes during rush hour and weekends are consistent throughout the day.](BikeSharing_files/figure-html/fig-graph7-1.png){#fig-graph7 fig-align='center' width=672}\n:::\n:::\n\n\nWow, looks like regardless of the season, people are commuting to/from work using this service (there’s a spike between 8 and 10 AM and another between 4 and 7 PM Monday through Friday). But the weekends seem to be popular between 10 AM and 6 PM.\n\n### Number of Trips by Member Type\nI wonder if different types of members (those who have a membership vs. those that bought a 24 hour or 3 day pass) vary in the number of trips they take.\n\nIf I were to guess, I’d think the short-term passes would be ideal for tourists or people looking for a quick weekend trip, whereas members may be more likely to continue using the service year-round. Let’s check out my assumptions by plotting, once again colored by season.\n\nTODO: workout compilation error in creation of `tripsPer_Month_UT`.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Line graph with 2 lines, one showing the number of trips per month, colored by season, for members, and one showing the number of trips per month, colored by season, for short-term pass holders. The shape is similar, but short-term passholders take fewer trips every month.](BikeSharing_files/figure-html/fig-graph8-1.png){#fig-graph8 fig-align='center' width=672}\n:::\n:::\n\n\nDifferent types of users (Member, Short-Term Pass Holder) seem to follow similar patterns of usage.\n\n### Trip Duration by Member Type\n\nWhile it may seem that the trip duration shouldn’t vary widely by member type, a historical understanding of Pronto!’s pricing structure may make you reconsider that assumption. You see, while you have to purchase either an annual membership ($85/year), a 24-Hour Pass ($8) or a 3-Day Pass ($16) there is still a cap on the duration of your trip. For members, any ride under 45 minutes is free, but any ride going over 45 minutes will incur a fee of $2 for every additional 30 minutes. For short-term users, any ride under 30 minutes is free, but going over that time limit would cost you an additional $2 for the first 30 minutes and $5 for each additional 30 minutes after that!\n\nLet’s see if these time limits cause differing behaviors in our users.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nstart_date_ym |>  \n   filter(usertype != \"\") |> \n   group_by(usertype) |>  \n   summarize(Trips = n()) |> \n   knitr::kable() \n```\n\n::: {.cell-output-display}\n|usertype               | Trips|\n|:----------------------|-----:|\n|Member                 | 35386|\n|Short-Term Pass Holder | 15406|\n:::\n\n```{.r .cell-code}\nstart_date_ym <- start_date_ym |>  \n   filter(usertype != \"\") |>  \n   mutate(tripduration_min = tripduration/60)\n```\n:::\n\n\nTODO: Change theme to match, but I have the raw graph done.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Two side-by-side histograms, showing member and short term pass holder trip duration with a black dotted line indicating the time when fees start accruing. Short-Term Pass Holders take a wider range of trip lengths and pay more fees.](BikeSharing_files/figure-html/fig-graph9-1.png){#fig-graph9 fig-align='center' width=672}\n:::\n:::\n\n\nOk, so our members are pretty good about making sure that they return their bike before they incur extra charges, but the short-term pass holders frequently go over their time limit. I wonder how the cost of a trip varies for members and pass holders. Let’s try to calculate the cost of a trip.\n\nNeed to compute cost properly!\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nstart_date_ym <- start_date_ym  |>\n  mutate(cost = ifelse(usertype == \"Member\" & tripduration_min <= 45, 0,\n    ifelse(usertype == \"Member\" & tripduration_min > 45 & tripduration_min <= 75, 2,\n      ifelse(usertype == \"Member\" & tripduration_min > 75, (2 + 2 * ceiling((tripduration_min - 75) / 30)),\n        ifelse(usertype == \"Short-Term Pass Holder\" & tripduration_min <= 30, 0,\n          ifelse(usertype == \"Short-Term Pass Holder\" & tripduration_min > 30 & tripduration_min < 60, 2,\n            ifelse(usertype == \"Short-Term Pass Holder\" & tripduration_min > 60, (2 + 5 * ceiling((tripduration_min - 60) / 30)), NA\n            )\n          )\n        )\n      )\n    )\n  ))\n```\n:::\n\n\nThat was a complicated nested if/else statement! Let’s see how much these folks are paying in additional fees!\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Two bar graphs side by side, showing member and short-term pass holder fee paying behavior. Short-term pass holders pay more fees.](BikeSharing_files/figure-html/fig-graph10-1.png){#fig-graph10 fig-align='center' width=672}\n:::\n:::\n\n\nLooks like short-term pass holders (who are already paying a higher price per day of biking), are also paying lots of extra fees. This could be because they are unfamiliar with the pricing structure and don’t realize they need to return their bike to a station within 30 minutes without getting charged. It is also possible that short-term users may be tourists who don’t know their way around as easily, and thus can’t find their way to a station within the time limit.\n\n### Member Demographics\n\nWe only seem to have age and gender information about people who have an annual Pronto! membership, so we can at least take a look at what types of people use this service.\n\nLet’s look first at age.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nstart_date_ym <- start_date_ym |>\n  mutate(age = year(start_dt) - birthyear)\nstart_date_ym |> \n  summarize(q25 = quantile(age, .25, na.rm = TRUE), q75 = quantile(age, .75, na.rm = TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  q25 q75\n1  28  41\n```\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(data = start_date_ym, aes(x = age)) +\n  geom_histogram(\n    fill = \"lightblue\",\n    color = \"black\",\n    binwidth = 2\n  ) +\n  theme_bw() +\n  labs(x = \"Age in years\")\n```\n\n::: {.cell-output-display}\n![Histogram showing that the middle 50% of riders are between the ages of 28 and 41.](BikeSharing_files/figure-html/fig-graph11-1.png){#fig-graph11 fig-align='center' width=672}\n:::\n:::\n\n\nMy first instinct here is to say “Wow! There’s a lot of 30-somethings that use this service!” But this figure (and these data) may be a little misleading. You see, we don’t have any sort of Rider ID number, meaning we can’t take “individual activity level” into account. So we can’t tell if the tallest spike is because 6 very athletic 28-year-olds went on 1,000 trips each, or if 100 people went on 60 trips each, or if there were 6,000 28-year-olds who each only used the service once.\n\nThe same problem would arise if we looked at gender, so I’m just going to move beyond demographics.\n\n_____\n\n## Skip the Trip Routes\n___\n\n# Exploring the Weather Dataset\n\nNow that I’ve visualized all that I can think of in terms of the “trips”” dataset, it’s time to take a brief look at the weather dataset.\n\nLet’s get a quick reminder of what we’re looking at here.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n```\nRows: 689\nColumns: 21\n$ Date                       <chr> \"10/13/2014\", \"10/14/2014\", \"10/15/2014\", \"…\n$ Max_Temperature_F          <int> 71, 63, 62, 71, 64, 68, 73, 66, 64, 60, 62,…\n$ Mean_Temperature_F         <int> 62, 59, 58, 61, 60, 64, 64, 60, 58, 58, 55,…\n$ Min_TemperatureF           <int> 54, 55, 54, 52, 57, 59, 55, 55, 55, 57, 50,…\n$ Max_Dew_Point_F            <int> 55, 52, 53, 49, 55, 59, 57, 57, 52, 55, 49,…\n$ MeanDew_Point_F            <int> 51, 51, 50, 46, 51, 57, 55, 54, 49, 53, 47,…\n$ Min_Dewpoint_F             <int> 46, 50, 46, 42, 41, 55, 53, 50, 46, 48, 44,…\n$ Max_Humidity               <int> 87, 88, 87, 83, 87, 90, 94, 90, 87, 88, 86,…\n$ Mean_Humidity              <int> 68, 78, 77, 61, 72, 83, 74, 78, 70, 81, 76,…\n$ Min_Humidity               <int> 46, 63, 67, 36, 46, 68, 52, 67, 58, 67, 62,…\n$ Max_Sea_Level_Pressure_In  <dbl> 30.03, 29.84, 29.98, 30.03, 29.83, 29.96, 2…\n$ Mean_Sea_Level_Pressure_In <dbl> 29.79, 29.75, 29.71, 29.95, 29.78, 29.90, 2…\n$ Min_Sea_Level_Pressure_In  <dbl> 29.65, 29.54, 29.51, 29.81, 29.73, 29.80, 2…\n$ Max_Visibility_Miles       <int> 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,…\n$ Mean_Visibility_Miles      <int> 10, 9, 9, 10, 10, 8, 10, 10, 10, 6, 10, 10,…\n$ Min_Visibility_Miles       <int> 4, 3, 3, 10, 6, 2, 6, 5, 6, 2, 10, 8, 6, 10…\n$ Max_Wind_Speed_MPH         <int> 13, 10, 18, 9, 8, 10, 10, 12, 15, 14, 15, 8…\n$ Mean_Wind_Speed_MPH        <int> 4, 5, 7, 4, 3, 4, 3, 5, 8, 8, 9, 4, 6, 12, …\n$ Max_Gust_Speed_MPH         <chr> \"21\", \"17\", \"25\", \"-\", \"-\", \"-\", \"18\", \"-\",…\n$ Precipitation_In           <dbl> 0.00, 0.11, 0.45, 0.00, 0.14, 0.31, 0.00, 0…\n$ Events                     <chr> \"Rain\", \"Rain\", \"Rain\", \"Rain\", \"Rain\", \"Ra…\n```\n:::\n:::\n\n\nGreat, let’s change the Date variable to a `POSIXct` object, and make the `Events` variable factors.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Adjusting the Date Variable\nweather$Date <- mdy(weather$Date)\n\n# Adjusting the Events Variable\nweather$Events <- as.factor(weather$Events)\n```\n:::\n\n\nGreat. Now how many weather events are there?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlevels(weather$Events)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"\"                    \"Fog\"                 \"Fog , Rain\"         \n [4] \"Fog-Rain\"            \"Rain\"                \"Rain , Snow\"        \n [7] \"Rain , Thunderstorm\" \"Rain-Snow\"           \"Rain-Thunderstorm\"  \n[10] \"Snow\"               \n```\n:::\n:::\n\n\nWow! So mostly combinations of rain.\n\nLet’s combine a few of these things that seem to represent the same event.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nweather$Events <- gsub(\"Fog , Rain|Fog-Rain\", \"Fog-Rain\", weather$Events)\nweather$Events <- gsub(\"Rain , Snow|Rain-Snow\", \"Rain-Snow\", \n    weather$Events)\nweather$Events <- gsub(\"Rain , Thunderstorm|Rain-Thunderstorm\", \n    \"Rain-TS\", weather$Events)\nweather$Events <- as.factor(weather$Events)\nlevels(weather$Events)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"\"          \"Fog\"       \"Fog-Rain\"  \"Rain\"      \"Rain-Snow\" \"Rain-TS\"  \n[7] \"Snow\"     \n```\n:::\n:::\n\n\nWhere else does this dataset need to be cleaned up? Let’s look for any missing values.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(weather)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      Date            Max_Temperature_F Mean_Temperature_F Min_TemperatureF\n Min.   :2014-10-13   Min.   :39.00     Min.   :33.00      Min.   :23.00   \n 1st Qu.:2015-04-03   1st Qu.:55.00     1st Qu.:48.00      1st Qu.:43.00   \n Median :2015-09-22   Median :63.00     Median :56.00      Median :50.00   \n Mean   :2015-09-22   Mean   :64.03     Mean   :56.58      Mean   :49.45   \n 3rd Qu.:2016-03-12   3rd Qu.:73.00     3rd Qu.:65.00      3rd Qu.:57.00   \n Max.   :2016-08-31   Max.   :98.00     Max.   :83.00      Max.   :70.00   \n                                        NA's   :1                          \n Max_Dew_Point_F MeanDew_Point_F Min_Dewpoint_F   Max_Humidity   \n Min.   :10.00   Min.   : 4.00   Min.   : 1.00   Min.   : 40.00  \n 1st Qu.:44.00   1st Qu.:41.00   1st Qu.:36.00   1st Qu.: 78.00  \n Median :50.00   Median :46.00   Median :42.00   Median : 86.00  \n Mean   :48.57   Mean   :45.02   Mean   :40.87   Mean   : 84.54  \n 3rd Qu.:54.00   3rd Qu.:51.00   3rd Qu.:47.00   3rd Qu.: 90.00  \n Max.   :77.00   Max.   :59.00   Max.   :57.00   Max.   :100.00  \n                                                                 \n Mean_Humidity    Min_Humidity   Max_Sea_Level_Pressure_In\n Min.   :24.00   Min.   :15.00   Min.   :29.47            \n 1st Qu.:60.00   1st Qu.:38.00   1st Qu.:30.01            \n Median :70.00   Median :50.00   Median :30.12            \n Mean   :68.51   Mean   :49.97   Mean   :30.12            \n 3rd Qu.:79.00   3rd Qu.:63.00   3rd Qu.:30.24            \n Max.   :95.00   Max.   :87.00   Max.   :30.86            \n                                                          \n Mean_Sea_Level_Pressure_In Min_Sea_Level_Pressure_In Max_Visibility_Miles\n Min.   :29.31              Min.   :29.14             Min.   : 3.00       \n 1st Qu.:29.93              1st Qu.:29.84             1st Qu.:10.00       \n Median :30.04              Median :29.96             Median :10.00       \n Mean   :30.03              Mean   :29.94             Mean   : 9.99       \n 3rd Qu.:30.16              3rd Qu.:30.08             3rd Qu.:10.00       \n Max.   :30.81              Max.   :30.75             Max.   :10.00       \n                                                                          \n Mean_Visibility_Miles Min_Visibility_Miles Max_Wind_Speed_MPH\n Min.   : 1.00         Min.   : 0.000       Min.   : 4.00     \n 1st Qu.: 9.00         1st Qu.: 4.000       1st Qu.: 8.00     \n Median :10.00         Median : 9.000       Median :10.00     \n Mean   : 9.43         Mean   : 7.245       Mean   :11.09     \n 3rd Qu.:10.00         3rd Qu.:10.000       3rd Qu.:13.00     \n Max.   :10.00         Max.   :10.000       Max.   :30.00     \n                                                              \n Mean_Wind_Speed_MPH Max_Gust_Speed_MPH Precipitation_In       Events   \n Min.   : 0.000      Length:689         Min.   :0.0000            :361  \n 1st Qu.: 3.000      Class :character   1st Qu.:0.0000   Fog      : 16  \n Median : 4.000      Mode  :character   Median :0.0000   Fog-Rain : 13  \n Mean   : 4.631                         Mean   :0.1051   Rain     :287  \n 3rd Qu.: 6.000                         3rd Qu.:0.0900   Rain-Snow:  3  \n Max.   :23.000                         Max.   :2.2000   Rain-TS  :  7  \n                                                         Snow     :  2  \n```\n:::\n:::\n\n\nOk, so we have one `NA` for `Mean_Temperature_F`, `Max_Gust_Speed_MPH` seems to be represented as a character vector because it has `-` representing `NA` values, and we have 361 unlabelled `Events`.\n\nMax Gust Speed should be the easiest one to fix, so we’ll start there.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nweather$Max_Gust_Speed_MPH <- gsub(\"-\", 0, weather$Max_Gust_Speed_MPH)\n\nweather$Max_Gust_Speed_MPH <- as.numeric(weather$Max_Gust_Speed_MPH)\n\nsummary(weather$Max_Gust_Speed_MPH)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n   0.00    0.00   17.00   12.65   22.00   52.00     185 \n```\n:::\n:::\n\n\nGreat! We changed any absent values for Maximum Gust Speed to 0 MPH and changed the variable type to a number. Uh oh, looks like there are still 185 `NA` values for Max Gust Speed. That’s a lot to try to replace. I would normally suggest generating a model that could try to predict those values based on other known values, but for now, we’ll just leave it alone.\n\nSince there is only one missing Mean Temperature, it seems the easiest way to fill in the hole is to look up what the average temperature was that day. Note: I certainly would not recommend this if it were any more than one *missing* value.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nweather[which(is.na(weather$Mean_Temperature_F)), 1]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"2016-02-14\"\n```\n:::\n:::\n\n\nOk, so we’re looking for the Mean Temperature on February 14, 2016 in the zipcode 98101 (according to dataset documentation). Looks like the mean temperature that day was 50 degrees F.\n\nTime to substitute in that value.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nweather[490, \"Mean_Temperature_F\"] <- 50\n```\n:::\n\n\nPerfect. Now what to do with the unlabelled `Event` categories. The dataset `ReadMe` file from Pronto! doesn’t include any information about this weather dataset. The only thing I can think to do is refer to the Event as `Other.`\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nweather$Events <- gsub(\"^$\", \"Other\", weather$Events)\nweather$Events <- as.factor(weather$Events)\n```\n:::\n\n\nOk, we’re in good shape. Now to do a few quick visualizations.\n\n## Temperature\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Line graph showing fluctuating daily minimum temperatures in Seattle](BikeSharing_files/figure-html/fig-graph12-1.png){#fig-graph12 fig-align='center' width=672}\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Line graph showing fluctuating daily mean temperatures in Seattle](BikeSharing_files/figure-html/fig-graph13-1.png){#fig-graph13 fig-align='center' width=672}\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Line graph showing fluctuating daily maximum temperatures in Seattle](BikeSharing_files/figure-html/fig-graph14-1.png){#fig-graph14 fig-align='center' width=672}\n:::\n:::\n\n\n## Events\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Bar graph showing that the most common weather events were `Rain` and `Other`.](BikeSharing_files/figure-html/fig-graph15-1.png){#fig-graph15 fig-align='center' width=672}\n:::\n:::\n\n\n## Combining Weather and Trip Datasets\n\nGood, so we can now see some parts of the weather data. Let’s combine the weather data with our trip data. Let’s try a `left join` from the `dplyr` package.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Make a copy of the data frame\ntrip_3 <- trip_2\n\n# Change column name in trip_3 to match weather dataset\ntrip_3$Date <- trip_3$start_date\n\n# Left join the trip and weather dataframes by date.\ntrip_weather <- left_join(trip_3, weather, by = \"Date\")\n# summary(trip_weather)\n```\n:::\n\n\n## Mean Temperature vs. Number of Trips\n\nOk. Now let’s see how the number of trips per day is influenced by weather (mean temperature, rounded to the nearest 5 degrees F).\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Line graph showing that the number of trips peaks when temperatures are around 50 degrees with higher or lower temperatures resulting in fewer rides.](BikeSharing_files/figure-html/fig-graph16-1.png){#fig-graph16 fig-align='center' width=672}\n:::\n:::\n\n\nInteresting! There are more trips when the weather is 50 F. I would have thought that to be too cold to want to ride. However, this figure may be influenced by the overall number of days that exhibited each mean temperature. Let us standardize.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nT1 <- trip_weather  |>  \n  mutate(RoundedTemp = round(Mean_Temperature_F/5)*5)  |> \n  group_by(RoundedTemp)  |>  \n  summarize(n = n(), Days = n_distinct(Date))  |>  \n  mutate(Ratio = n/Days)\nT1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 7 × 4\n  RoundedTemp     n  Days Ratio\n        <dbl> <int> <int> <dbl>\n1          35  1074     7  153.\n2          40  4522    19  238 \n3          45  5963    24  248.\n4          50 20081    74  271.\n5          55  9695    35  277 \n6          60  8393    26  323.\n7          65  1065     2  532.\n```\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Line graph showing that bike rides increased with an increase in temperature, relative to the number of days at each temperature.](BikeSharing_files/figure-html/fig-graph17-1.png){#fig-graph17 fig-align='center' width=672}\n:::\n:::\n\n\nSo when we standardize our measurements, correcting for the number of days that actually reached each temperature, we see a steady increase in the number of trips until around 65 F. People are more likely to ride a bike when it’s warm outside.\n\n## Precipitation vs. Number of Trips\n\nIf you’ve ever heard of Seattle, you probably hear that it rains all the time there. Let’s see if that has an impact on the number of trips taken in a day.\n\nWe’ll start with a figure standardized for number of days at a precipitation level, rounded to the nearest 0.2 inches.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nT2 <- trip_weather |>  \n  mutate(RoundedPrecip = round(Precipitation_In / 0.2)*0.2) |> \n  group_by(RoundedPrecip) |>  \n  summarize(n = n(), Days = n_distinct(Date)) |>  \n  mutate(Ratio = n/Days)\nT2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 7 × 4\n  RoundedPrecip     n  Days Ratio\n          <dbl> <int> <int> <dbl>\n1           0   37773   129  293.\n2           0.2  6558    27  243.\n3           0.4  3777    15  252.\n4           0.6  1393     7  199 \n5           0.8  1055     6  176.\n6           1.4   203     2  102.\n7           2.2    34     1   34 \n```\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Line graph showing that the number of trips dropped as the precipitation level increased.](BikeSharing_files/figure-html/fig-graph18-1.png){#fig-graph18 fig-align='center' width=672}\n:::\n:::\n\n\nLooks like even Seattleites have a limit when it comes to riding a bike in the rain. The more it rained, the fewer trips were taken per day.",
    "supporting": [
      "BikeSharing_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}